### PR TITLE
added blog post about improving joins

### PR DESCRIPTION
**Pull request by chaudum**

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
I'll take a quick look if you like @chaudum as I was about to review another anyway :)

**Comment by ChrisChinchilla** [comment]
@chaudum Made some tweaks and americanized the language much against my better judgement ;)

**Comment by mikethebeer** [comment]
looks gud from my side :santa:

**Comment by ChrisChinchilla** [comment]
@chaudum and @mikethebeer I will merge in tomorrow along side another blog post.

**Comment by chaudum** [comment]
@ChrisChinchilla I'm not sure if we should release this blog post prior to releasing the new improvements in a testing release. What do you think?

**Comment by ChrisChinchilla** [comment]
@chaudum Definitely! I guess I assumed it was in a testing release. No point having a blog post if no-one can get their hands on something. Let me know when it is in a testing release.

**Pull request merged**
