### PR TITLE
Added Crate-jdbc 1.6 release

### PR DESCRIPTION
**Pull request by ChrisChinchilla**

### CODE REVIEW

**Comment by tbrandles** [comment]
ACK but are we putting client releases into the blog? I know we aren't putting crate/crate releases in.

**Comment by ChrisChinchilla** [comment]
I'm not sure what you mean @tbrandles ? I have no idea to be honest and just copied what had happened in the past, if this has changed then let me know what I need to do instead and where we should announce client and core releases as I have a few to add.

**Comment by chaudum** [comment]
@ChrisChinchilla @tbrandles you need to decide what to put on the blog. I agree with tyler that client releases are somehow polluting the blog...

**Comment by ChrisChinchilla** [comment]
As someone needs to decide on something. I say we have a monthly update post on all client updates, then that can be merged into social media, newsletters etc.

What say you @tbrandles and @chaudum ?

**Pull request closed without merging**
